INSERT INTO CURRENCY VALUES('SEK')
INSERT INTO CURRENCY VALUES('ISK')
INSERT INTO CURRENCY VALUES('USD')
INSERT INTO CURRENCY VALUES('EUR')

INSERT INTO RATE VALUES (1,1,'SEK','SEK')
INSERT INTO RATE VALUES (2,1,'USD','USD')
INSERT INTO RATE VALUES (3,1,'ISK','ISK')
INSERT INTO RATE VALUES (4,1,'EUR','EUR')

INSERT INTO RATE VALUES (5,0.11,'SEK','USD')
INSERT INTO RATE VALUES (6,12.12,'SEK','ISK')
INSERT INTO RATE VALUES (7,0.1,'SEK','EUR')

INSERT INTO RATE VALUES (8,0.082,'ISK','SEK')
INSERT INTO RATE VALUES (9,0.0090,'ISK','USD')
INSERT INTO RATE VALUES (10,0.0084,'ISK','EUR')

INSERT INTO RATE VALUES (11,110.55,'USD','ISK')
INSERT INTO RATE VALUES (12,0.93,'USD','EUR')
INSERT INTO RATE VALUES (13,9.12,'USD','SEK')

INSERT INTO RATE VALUES (14,10,'EUR','SEK')
INSERT INTO RATE VALUES (15,1.07,'EUR','USD')
INSERT INTO RATE VALUES (16,118.60,'EUR','ISK')